version: "3.8"
services:
  client:
    container_name: movies-app-front
    image: movies-app-front
    build:
      context: ./movies-app
    volumes:
      - ./movies-app/src:/src
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV="development"

  api:
    container_name: movies-app-api
    image: movies-app-api
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    ports:
      - "3001:3001"
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - DATABASE_URL=postgres://root:password@postgres-db/
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - RAILS_ENV="development"
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 5s
      retries: 30
